general.import = [
  "themes/github.toml",
  # "themes/catppuccin-mocha.toml",
  # "wsl.toml",
]

[window]
decorations = "none"
startup_mode =  "Maximized"
opacity = 0.85
padding = {x = 5, y = 5}

[font]
normal.family = "Hack Nerd Font"
